Added path resolve in webpack config to allow for builds on windows platforms
epixa/tbyn pull request #3
Opened 2017-04-24 19:38 UTC by stephanfx

Added JSHint file

2017-04-24 21:56 UTC, epixa requested changes
There are just some linting issues on this PR, which I've identified inline.  You can always double check that code adheres to the style rules by running `npm run lint`

I should also get pull requests working with circle-ci so they could be flagged automatically, but that's a separate thing.

2017-04-24 21:56 UTC, epixa commented on webpack.config.js
> +var path = require('path');
Can you change this to a `const` instead?

2017-04-24 21:56 UTC, epixa commented on webpack.config.js
> +        path.resolve('lib')
These lines are indented too far, can you remove two spaces?

2017-04-25 14:35 UTC, epixa approved these changes

2017-04-25 14:35 UTC, merged

2017-04-25 14:35 UTC, epixa commented
Thanks for the pull request!

2017-04-25 15:38 UTC, emudojo commented
yay, this helps quite a bit, thanks @stephanfx and @epixa